baseURL = "https://stoneepigraph.github.io/"
languageCode = "zh-CN"
title = "石记"
description = "不会修自行车的建筑师不是一个好的程序员."
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-monochrome"
enableEmoji = true
publishdir = "docs"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
version = "0.2.2"
author = "Stone Epigraph"
defaultTheme = "dark"
enable_site_search = true
