[[navbar]]
  identifier = "setup"
  name = "posts"
  url = "/posts/"
  weight = 1
[[navbar]]
  identifier = "categories"
  name = "Categories"
  url = "/categories"
  weight = 2
[[navbar]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 3
[[navbar]]
  identifier = "Others"
  name = "Others"
  url = "/Others/"
  weight = 5
[[navbar]]
  identifier = "Abouts"
  name = "Abouts"
  url = "/abouts"
  weight = 9
  [[navbar]]
    identifier = "About"
    name = "About"
    parent = "Abouts"
    url = "/abouts/about"
    weight = 1
  [[navbar]]
    identifier = "Contact"
    name = "Contact"
    parent = "Abouts"
    url = "/abouts/contact"
    weight = 2
